### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by liwentao-123** [xlwang233/STSeq2Seq#1]
Hello Author:

I have met a error while I was running this command:'python eval_baseline.py' because I want to eval the baseline method. the error is concretely as follows:
 File "eval_baselines.py", line 214, in <module>
    logger = utils.get_logger('../saved/baselines/METR-LA', 'Baseline')
...
  FileNotFoundError: [Errno 2] No such file or directory: 'E:\\STSeq2Seq-master\\saved\\baselines\\METR-LA\\info.log'

 So ,how to deal with this problem?I appreciate it if you answer me fast

**Comment by xlwang233** [comment]
Hi, liwentao,

I think you get this error because the directory is not there and you have to create it before you run the script. So just create the directory '.../saved/baselines/METR-LA' mannually and the problem should be gone.
